# Generated by Django 2.1.2 on 2018-10-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='like',
        ),
    ]
