# Generated by Django 2.1.2 on 2018-10-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_gift_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Gift')),
            ],
        ),
    ]
